pico/media.c, pico/pico.c, pico/pico.h, pico/sound/sound.c, platform/libretro/libretro.c
This new core option will override the Region option.
So it's possible to choose the Europe Region and the NTSC FPS.
Strangely the region protection has no effect on megadrive :-)
But will happend on 32x and SegaCD (Maybe it can be fixed by activating
this core option after a little delay on startup)
=> Add core option to force the Region FPS (NTSC, PAL)

Makefile
- Use DEBUG flag similar to other libretro cores (DEBUG=0 disables, DEBUG=1 enables the debug build)
- Optimize with -O2 for debugging because the core won't work otherwise
- Always strip sections to prevent undefined symbol errors
See https://github.com/libretro/picodrive/issues/29
=> Fix compilation with DEBUG flag

Makefile, pico/sound/ym2612.c
This does two things, first it makes it so that it will check if DEBUG is set rather than if its not set. Debug builds should be intentional behavior.
Second this will change debug builds from `-O2` to `-O0` which is correct behavior for debug builds which should not be built with optimizations. The downside is that this will not correctly work with picodrive, but its probably better to expose an issue and then later solve it than to mask it until it causes problems later which are harder to diagnose.
See:
https://github.com/libretro/picodrive/pull/40
https://github.com/libretro/picodrive/issues/29
=> Check if DEBUG is set rather than not set.

Makefile.libretro, jni/Android.mk, platform/libretro/libretro.c
This patch makes this core report the git version along with its library_version. This is important because otherwise it is impossible to replicate a build without extra knowledge, and things like Netplay that demand versions be the same can't be reliably known to work.
=> Report git version with library_version

pico/patch.c, platform/libretro/libretro.c
Fixes #25 and then some
Adds support for Game Genie, Genecyst patch, and Action Replay cheats within PicoDrive.
Should also function for Sega CD and 32X games.
Master System cheats not supported, as the Master System has a separate code format not supported by upstream Picodrive.
Game Genie cheats can be formatted as: AAAA-AAAA or AAAAAAAA
Genecyst Patch and Action Replay cheats can be formatted as: 000000:FF or 000000:FFFF
Multiline cheats supported, so long as + is used as a delimiter.
=> Add cheat support for Genesis/MegaDrive, CD, and 32X games

pico/memory.c, pico/patch.c, pico/patch.h, platform/libretro/libretro.c
With this pull request, Picodrive now supports the following cheat types:
Global:
* Multiline: {cheat}+{cheat}
Genesis [and CD/32X?]:
* Game Genie AAAA-AAAA
* Patch 012345:6789
* Action Replay FF1234:5678
Master System:
* Game Genie ABC-DEF-GHJ and ABC-DEF
* Action Replay 0012-3456
* Fusion 0123:45 and 670123:45
Barring any bugs I missed or requests for other code formats, this can be considered complete.
=> Add support for Master System cheats.

Makefile.libretro
Issue is caused by commit 66dda842eae01f47f5389b931ec9567fb0bbb6a1 in
cpu/cyclone submodule.
=> libretro: fix unexpected reloc type 0x03 error on Raspberry Pi 3

Makefile, Makefile.libretro
This allows the Picodrive core to build on Solaris 11 by simply running `gmake -f Makefile.libretro`
=> Picodrive core for Solaris

platform/libretro/libretro.c, platform/libretro/libretro_core_options.h
I've added an option to change the renderer from the default "accurate" line-based renderer to an alternative "fast" tile-based renderer, which may improve performance on slower devices such as the PSP. (This was already an option on the native PSP build of picodrive: https://github.com/libretro/picodrive/blob/master/platform/psp/emu.c#L751)
Fixes #112
=> Add renderer option

platform/libretro/libretro.c, platform/libretro/libretro_core_options.h
Even with the fast renderer (#116), the framerate on the PSP slows down at some points in some games. Reducing the sound rate can help increase the framerate in these cases.
It's not ideal but it's better than frame skipping.
=> Add option to change sound quality

.gitignore, Makefile.libretro, pico/cd/cue.c, platform/libretro/libretro.c, platform/libretro/libretro_core_options.h
At present, the `MegaCD RAM cart` option doesn't function correctly: a RAM cart is emulated, but its contents is never saved to disk. This happens because the wrong buffer is exposed in `retro_get_memory_data()`.
This PR fixes the issue.
**Important note:** BRAM and RAM cart are mutually exclusive - if the RAM cart is enabled, BRAM saves will be discarded. This is because the libretro API only allows one data buffer to be accessed via `retro_get_memory_data()`. The core options sublabel has been updated to reflect this fact. Since there are very few (3?) games that require the use of a RAM cart anyway, I don't think this is a problem.
In addition, this PR:
- Fixes a heap buffer overflow in the cue parsing code (noticed while running with ASAN enabled)
- Trivially fixes the OpenDingux …
=> Fix MegaCD RAM cart saving

Makefile.libretro, platform/libretro/libretro.c
Prior to f8a685534411fdbd9d8b2bff994cff729d559f7e, we were mistakenly building the core for Vita in the PSP job of the gitlab pipeline. Now that we are attempting to build the correct PSP core, it seems that compilation fails due to an `undefined reference to '_flush_cache'` error.
This 'band-aid' PR fixes PSP compilation. I am unable to test whether the core actually runs on PSP, but this at least enables the gitlab pipeline to run successfully.
=> Fix PSP compilation

pico/cart.c, pico/media.c, pico/pico.h, platform/common/emu.c, platform/libretro/libretro-common/include/libretro.h, platform/libretro/libretro.c
This PR adds support for the new libretro `RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE` API extension introduced here: libretro/RetroArch#12473
Using this extension, the core's `need_fullpath` requirement is suspended for content of the following file types: `.gen`, `.smd`, `.md`, `.32x`, `.sms`
As a result:
- Frontend softpatching is now supported for these file types
- When loading these file types from compressed archives, it is no longer necessary for the frontend to extract the content to a temporary file on-disk
=> Add support for RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE API extension - enables soft patching of non-CD content

platform/libretro/libretro.c
This trivial PR fixes an improper cast due to a typo. This is harmless, since the affected buffer is implicitly cast to the correct type immediately after, but typos should not be tolerated....
=> Fix minor typo (harmless cast of a buffer to an incorrect type)

Makefile.libretro, platform/libretro/libretro.c
This PR adds a `LOW_MEMORY` build flag which forces the core to set `need_fullpath = true` - meaning that ROM data will be read directly from file rather than being passed as a frontend-provided data buffer. This is required for very low memory platforms, where the use of an 'external' memory buffer (which must be duplicated in the core) can exceed the total system RAM.
At present, this flag is only enabled for the RS-90 build. This allows 4MB ROMs to be loaded successfully (without the flag, the core will simply crash when attempting to launch such content)
=> Add 'LOW_MEMORY' build flag to force content loading from file on RAM-limited platforms

platform/libretro/libretro.c
This PR adds the `Sega Mega Drive and Genesis Classics` ROM file types (`.68k` and `.sgd`) to the valid extensions list. These were previously added to the core info file without updating the core itself, leading to issues when loading content.
=> Add 'Sega Classics' file types (.68k, .sgd) to valid extensions

platform/libretro/libretro.c, platform/libretro/libretro_core_options.h
This adds an option for Master System games to either cut off 8 pixels from the left side of the screen only, or 8 pixels from both left and right sides.
=> Add "Hide Master System Side Borders" option

platform/libretro/libretro.c, platform/libretro/libretro_core_options.h
Reverts 8df78bec3d10daa56fa97d9438f502d5f0d1f7a0, as PicoDrive already seems to deal with the Master System left border in a different way, which conflicts with the "Hide Master System Side Borders" option.
=> Revert "Ported over the 'Hide Master System Side Borders' option from Genesis-Plus-GX to PicoDrive".

platform/libretro/libretro_core_options.h
Should bring back the core option that were accidentally broken in the revert of #176
=> Fix accidental line remove in previous revert.

pico/media.c
This PR fixes a segfault when loading SMS/GG ROMs, due to an invalid string comparison in `PicoLoadMedia()` (when using the libretro core, a required 'file extension' field is not set; it is therefore necessary to extract this 'on demand' from the content filename)
=> Fix loading of SMS/GG ROMs

Makefile.libretro
PicoDrive's Arm cores building need HAVE_ARMv6 = 0 for Miyoo.
=> add HAVE_ARMv6 = 0 + minor fixes

platform/libretro/libretro.c
VFS callbacks fail since it requires V2, which includes vfs_truncate. Otherwise it falls back to libretro-common code. Current VFS wrapping code in libretro-common needs V2 since vfs_truncate's callback is set.
https://github.com/libretro/libretro-common/blob/master/streams/file_stream.c#L65
Now VFS callbacks work properly in frontends that support them. Otherwise a hack of setting "cb->required_interface_version = 2" in frontend works. Only cores, according to specs, are meant to set the required version.
=> Use proper VFS version.

Makefile.libretro
This PR fixes a build error on Windows. The error is due to the root directory not explicitly added by the compiler.
Before, error was:
```
platform/common/mp3.c:11:10: fatal error: pico/pico_int.h: No such file or directory
11 | #include <pico/pico_int.h>
|          ^~~~~~~~~~~~~~~~~
```
After, the core builds successfully.
(I'm hunting down a link of our last successful CI run)
=> Fix build error on Windows

platform/libretro/libretro.c
This PR expose byte slice of Video Memory and Color Memory on libretro picodrive core
to allow creation of debugger frontends using libretro.
=> Expose VRAM and CRAM on libretro to allow creation of debugger frontend

Makefile.libretro
This is needed after c36ff0fdff4cc08c9b00a2412af113f05c6571dd see comments in https://github.com/libretro/RetroArch/pull/17422
=> Try to fix emscripten build

Makefile.libretro
I made a mistake in a previous commit - the fix for emscripten should not be shared with all builds, just localized to the emscripten build.
Sorry for the noise.
=> Try to fix emscripten build without breaking other builds
