platform/libretro/libretro.c
Finally we will be able to play Cosmic Carnage in its fully uncensored glory!
=> (libretro) Implement region switch

platform/libretro/libretro.c
Rename by adding 'Button' prefix for more clarity #19
=> Rename input descriptors label for MasterSystem

Makefile.libretro, platform/libretro/psp/draw_amips.s
Create platform/libretro/psp and copy draw_amips.s into it
Add draw_amips.o to psp OBJS
=> PSP build fix

platform/libretro/libretro.c
Primary **RETRO_MEMORY_SYSTEM_RAM** support, allow to libretro get cheevos on this system.
Thanks for review this code!
=> allow request RETRO_MEMORY_SYSTEM_RAM to get cheevos

platform/libretro/libretro.c
The core option let you choose between 3 aspect ratios.
PAR: Native resolution
DAR: 4/3
CRT: Thinner than 4/3, I did some comparison with my old CRT TV.
I did another change to take in account the 224 instead of 240 vertical
resolution to fix the integer scale
Related issue #7, #15 and #26
=> Add a core option to choose between PAR, DAR and CRT aspect ratio

Makefile.libretro, pico/cart.c
This also seems to reduce a bit of stutter in some games (like sonic 3)
Thanks to @frangarcj for figuring out the workaround
=> (VITA) Removed gross hack with optimization workaround

Makefile, Makefile.libretro, cpu/drc/cmn.c, cpu/drc/cmn.h, platform/libretro/libretro.c
Based heavily on @frangarcj's work for pcsx_rearmed
=> (VITA) Dynarec working

pico/sound/ym2612.c
I didn't properly `git commit --amend` before submitting my previous PR https://github.com/libretro/picodrive/pull/41 last night, my bad...
=> Actually fix the debug build

pico/sound/ym2612.c
@orbea I got more undefined symbol errors when trying to start a game.
With this changes it works for me with and without gdb.
=> Fix more undefined symbol errors

pico/patch.c
The things you realize you forgot to retest until seconds after you submit the pull request, and then the pull request gets accepted in record time so you have to submit a new one.
=> Restore support for short GG cheats.

Makefile.libretro, platform/libretro/libretro.c
Builds and actually runs content.
=> libtransistor / Switch support.

Makefile.libretro, pico/mode4.c, platform/libretro/libretro-common/include/libretro_gskit_ps2.h, platform/libretro/libretro.c, platform/ps2/Draw_mips_r5900.s, platform/ps2/Memory_mips_r5900.s, platform/ps2/SMS_Utils.s, platform/ps2/asm.h, platform/ps2/asm.s
Implement the Palette for libretro and specifically for PS2.
In order to improve the performance I have added some assembly functions
=> [PS2] Implement the Palette

platform/libretro/libretro.c
As reported in issue #96, and on the forums (e.g. https://forums.libretro.com/t/picodrive-cropping-overscan-crops-too-much/21160), the output of the picodrive core is currently quite broken:
- With all content, disabling overscan shifts the image downwards and clips off the bottom of the display.
- With Master System content, this happens to an extreme extent whether or not overscan is enabled.
This is caused by a very silly bug, which this PR fixes. This PR also adds the ability to change the 'show overscan' setting while content is running.
This closes #96.
=> Fix display alignment/overscan cropping

Makefile.libretro
=> Add generic AARCH64

Makefile.libretro
So we can finally have 32X support for iOS/tvOS.
=> (iOS/tvOS): Support building for arm64

.travis.yml, Makefile, platform/common/common.mak
Dirty but may fix https://github.com/libretro/libretro-super/issues/1116
=> Compile cyclone with the host g++

platform/libretro/libretro-common/compat/fopen_utf8.c, platform/libretro/libretro-common/encodings/encoding_utf.c, platform/libretro/libretro-common/include/compat/getopt.h, platform/libretro/libretro-common/include/compat/intrinsics.h, platform/libretro/libretro-common/include/compat/msvc.h, platform/libretro/libretro-common/include/compat/msvc/stdint.h, platform/libretro/libretro-common/include/compat/posix_string.h, platform/libretro/libretro-common/include/compat/strcasestr.h, platform/libretro/libretro-common/include/compat/strl.h, platform/libretro/libretro-common/include/libretro.h, platform/libretro/libretro-common/include/memmap.h, platform/libretro/libretro-common/include/retro_common.h, platform/libretro/libretro-common/include/retro_common_api.h, platform/libretro/libretro-common/include/retro_dirent.h, platform/libretro/libretro-common/include/retro_environment.h, platform/libretro/libretro-common/include/retro_miscellaneous.h, platform/libretro/libretro-common/include/streams/file_stream.h, platform/libretro/libretro-common/include/streams/file_stream_transforms.h, platform/libretro/libretro-common/include/string/stdstring.h, platform/libretro/libretro-common/include/vfs/vfs_implementation.h, platform/libretro/libretro-common/streams/file_stream.c, platform/libretro/libretro-common/streams/file_stream_transforms.c, platform/libretro/libretro-common/string/stdstring.c, platform/libretro/libretro-common/vfs/vfs_implementation.c, platform/libretro/libretro.c
reference : https://github.com/libretro/Genesis-Plus-GX/issues/191
=> Update libretro-common, add Sega CD memory map

Makefile, cpu/sh2/compiler.c, pico/32x/memory.c, pico/draw.c, platform/libretro/libretro-common/compat/compat_posix_string.c, platform/libretro/libretro-common/include/file/file_path.h, platform/libretro/libretro-common/include/vfs/vfs.h
Fixed some non standard C that only works in GCC, added VS compatible arch defines, fixed VFS compilation
=> Fixed MSVC compilation, VFS

AUTHORS, Makefile, README.md, cpu/drc/emit_arm.c, cpu/drc/emit_arm64.c, cpu/drc/emit_mips.c, cpu/drc/emit_ppc.c, cpu/drc/emit_riscv.c, cpu/drc/emit_x86.c, cpu/sh2/compiler.c, pico/32x/draw.c, pico/cd/cdd.c, pico/draw.c, pico/draw2.c, pico/draw_arm.S, pico/m68kif_cyclone.s, pico/memory.c, pico/mode4.c, pico/pico.h, pico/pico_int.h, pico/sound/sound.c, pico/state.c, pico/videoport.c, platform/common/emu.c, platform/common/menu_pico.c, platform/gizmondo/emu.c, platform/linux/emu.c, platform/psp/emu.c
Irixxxx has been doing incredible work on Picodrive over at https://github.com/irixxxx/picodrive. This PR cherry picks his recent commits. There are a host of improvements here: bug and rendering fixes, and substantial performance gains.
Notes:
- I did not include the following optimisation commit because it conflicts with our local modifications for the PS2 port: https://github.com/irixxxx/picodrive/commit/352479001c82fc5c9abbcc1501c6e78ddc691a14 (I can't test on PS2, so didn't want to meddle with this)
- I did not include the new YM2413 audio emulation because this requires an additional submodule, and I cannot confirm that this builds/runs correctly on all platforms
=> Irixxxx updates

Makefile
This trivial PR fixes compilation on OSX
=> Fix OSX compilation

Makefile, pico/sound/mix.c, pico/sound/mix.h, pico/sound/mix_arm.S, pico/sound/sound.c, platform/common/inputmap_kbd.c, platform/common/plat_sdl.c, platform/common/plat_sdl.h, platform/libretro/libretro.c, platform/opendingux/inputmap.c
This PR merges the latest commits from irixxxx's upstream repo.
The main feature here is a new, very highly optimised replacement for the existing low pass audio filter. Many thanks to @irixxxx for the hours of work that went into this!
=> Merge latest commits from https://github.com/irixxxx/picodrive

Makefile.libretro
Add support for RS90. Compiles.
Haven't tested it yet.
=> Add support for RS90

Makefile.libretro
Added raspberry pi 2 and 3 in Make.libretro file.
=> Adding rpi2/3

.gitlab-ci.yml, Makefile, pico/cart.c
=> Fix Pico autodetection and emscripten

platform/libretro/libretro.c
Exposes the additional 256KB of SDRAM added by the 32x for use in cheats/achievements.
=> expose additional 32x memory
